version: '3.7'

services:
  app:
    container_name: outdoors-sports-map
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5000:5000'
