name: Build & Staging
on:
  push:
    branches:
      - develop

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: "build_artifacts"
  SERVICE_ARTIFACT_FOLDER: "service_artifacts"
  SERVICE_PORT: 80
  K8S_REQUEST_CPU: 1m
  K8S_REQUEST_RAM: 10Mi
  K8S_LIMIT_CPU: 20m
  K8S_LIMIT_RAM: 20Mi
  K8S_REPLICACOUNT: 2
  K8S_INGRESS_PREVENT_ROBOTS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_BUILD_ARG_REACT_APP_API_URL: "https://api.hel.fi/servicemap/v2"
          DOCKER_BUILD_ARG_REACT_APP_DIGITRANSIT_API_URL: "https://api.digitransit.fi/geocoding/v1"
          DOCKER_BUILD_ARG_REACT_APP_APP_NAME: "outdoors-sports-map"
          DOCKER_BUILD_ARG_REACT_APP_SITE_WIDE_NOTIFICATION_ENABLED: 1
          DOCKER_BUILD_ARG_REACT_APP_SITE_WIDE_NOTIFICATION_TITLE_FI: "Uimarantakausi 2022"
          DOCKER_BUILD_ARG_REACT_APP_SITE_WIDE_NOTIFICATION_TITLE_SV: "Badsäsongen 2022"
          DOCKER_BUILD_ARG_REACT_APP_SITE_WIDE_NOTIFICATION_TITLE_EN: "Beach season 2022"
          DOCKER_BUILD_ARG_REACT_APP_SITE_WIDE_NOTIFICATION_FI: "Pääkaupunkiseudun uimarantakausi on kesäkuusta elokuuhun (koululaisten kesäloman ajan). Tänä aikana uimaveden laatua seurataan säännöllisesti. Rantavalvottujen uimarantojen uimaveden lämpötilat sekä rantavalvojien silmämääräisesti tekemät sinilevähavainnot näkee suoraan kunkin uimarannan kohdalta. Rantojen tiedoista löytyvät myös linkit, joista pääsee siirtymään kyseisen kaupungin uimaveden laadunvalvonnan sivuille."
          DOCKER_BUILD_ARG_REACT_APP_SITE_WIDE_NOTIFICATION_SV: "Badsäsongen i huvudstadsregionen är från juni till augusti (under skolornas sommarlov). Under denna tid övervakas badvattnets kvalitet regelbundet. Badvattnets temperatur vid badstränder med badvakter och badvakternas visuella bedömningar av mängden av blågröna alger kan ses direkt vid respektive badstrand. I uppgifterna om badstränderna finns också länkar till webbsidan för kvalitetskontroll av badvattnet för staden i fråga."
          DOCKER_BUILD_ARG_REACT_APP_SITE_WIDE_NOTIFICATION_EN: "The beach season in the Helsinki Metropolitan Area is from June to August (during schoolchildren’s summer holiday). During this period, swimming water quality will be monitored regularly. The swimming water temperature at the monitored beaches and any blue-green algae sightings by the beach guards can be seen directly for each public beach. Beach details also contain links to the website of the swimming water quality monitoring by the respective city."

  staging:
    runs-on: ubuntu-latest
    needs: build
    name: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: "staging"
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
